http {
    upstream iot_monitoring {
        server iot-monitoring-1:8080;
        server iot-monitoring-2:8080;
        server iot-monitoring-3:8080;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://iot_monitoring;
        }
    }
}